# Site
theme: jekyll-theme-so-simple
skin: "/assets/css/skins/default.css"
locale: nl-NL
baseurl: ""
url: https://www.vandersluijs.nl # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: "/assets/images/logo.png"
date_format: "%A, %e %B %Y"
read_time: # reading time estimates, e.g. true
words_per_minute: # 200
mathjax:
  enable: # MathJax equations, e.g. true, false (default)
  combo: # "tex-svg" (default), "tex-mml-chtml", etc.: docs.mathjax.org/en/latest/web/components/combined.html
  tags: # "none", "ams" (default), "all"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: "UA-1497722-5"
disqus:
  shortname: vdsluijs # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: # site's Twitter username, e.g. "mmistakes"

name: "van der Sluijs"
title: "van der Sluijs"
description: "Dit is mijn oude site!!"
favicon: "/assets/images/logo.png"

include: ["_pages"]
permalink: /:title/

liquid:
  error_mode: strict

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
author:
  name: Theo van der Sluijs
  picture:
  email: theo@vandersluijs.nl
  twitter:
  links:
    - title:
      url:
      icon:

# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-redirect-from

#Timezone
timezone: "Europe/Amsterdam"

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# # Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "" # efg. ca-pub-3412143450191416
adsense-data-ad-slot: "" #eg. 1363087678

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Exclude
exclude:
  - screenshot.png
  - LICENSE.txt
  - sample_posts
  - Gemfile.lock
  - Gemfile
  - README.md
  - .Gruntfile.js
  - .vscode
  - node_modules
  - scss
  - css
  - _drafts
