# Site
name: "van der Sluijs"
title: "van der Sluijs"
description: "To boldly go where no blog has gone before!"
logo: "assets/images/logo.png"
favicon: "assets/images/logo.png"
baseurl: ""
google_analytics: "UA-1497722-5"
disqus: "vdsluijs"
mailchimp-list: ""
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  tvdsluijs:
    name: Theo van der Sluijs
    display_name: iTheo
    gravatar: b40d3b7da056fcc44bf7792e4ed4bda3
    email: theo@vandersluijs.nl
    web: https://www.itheo.nl
    twitter: https://twitter.com/tvdsluijs
    description: "Theo van der Sluijs 'tvdsluijs' is a Dutch professional Agile Servant Leader and Programmer, who has worked for Bax music and Glencore Agriculture. As a kid, he started developing software on a Commodore 64."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-redirect-from

#Timezone
timezone: "Europe/Amsterdam"

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "" # efg. ca-pub-3412143450191416
adsense-data-ad-slot: "" #eg. 1363087678

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Exclude
exclude:
  - screenshot.png
  - LICENSE.txt
  - sample_posts
  - Gemfile.lock
  - Gemfile
  - README.md
  - .Gruntfile.js
  - .vscode
  - node_modules
  - scss
  - css
  - _drafts
